return {
  pde = {
    ai = true,
    angular = true,
    cpp = true,
    csharp = false,
    docker = true,
    elixir = false,
    flutter = false,
    go = false,
    html = true,
    java = true,
    json = true,
    julia = false,
    jupyter = false,
    kotlin = false,
    lua = true,
    python = true,
    r = false,
    react = true,
    ruby = false,
    rust = false,
    scala = false,
    solidity = false,
    svelte = false,
    tailwind = true,
    terraform = false,
    typescript = true,
    vuejs = true,
  },
}
